import type { Profile, Statement } from '../profile/schema.js';

export function renderProfile(profile: Profile): string {
  const threshold = profile.render_threshold ?? 0.5;
  const lines: string[] = [];
  lines.push('# Developer Profile (generated by persona)');
  lines.push('');
  lines.push(`Scope: \`${profile.scope}\``);
  lines.push('');
  lines.push('## Identity');
  lines.push(`- **Name:** ${profile.identity.name}`);
  lines.push(`- **Languages:** ${profile.identity.primary_languages.join(', ') || '(none)'}`);
  lines.push(`- **Tools:** ${profile.identity.primary_tools.join(', ') || '(none)'}`);
  lines.push('');

  section(lines, 'Preferences', profile.preferences, threshold);
  section(lines, 'Conventions', profile.conventions, threshold);
  section(lines, 'Rationales', profile.rationales, threshold);

  lines.push('');
  lines.push('> Managed by `persona`. To correct, edit `profile.overrides.yaml` — do not edit this fence.');
  return lines.join('\n') + '\n';
}

function section(out: string[], title: string, statements: Statement[], threshold: number): void {
  const visible = statements.filter((s) => s.confidence >= threshold);
  if (!visible.length) return;
  out.push(`## ${title}`);
  for (const s of visible) {
    out.push(`- ${s.statement} (_conf ${s.confidence.toFixed(2)}_)`);
  }
  out.push('');
}
